services:
  - type: web
    name: api-news-back
    env: docker
    plan: free
    dockerfilePath: ./api-news-back/Dockerfile.prod
    dockerContext: ./api-news-back
    autoDeploy: true
    envVars:
      - key: BACK_MONGODB_URI
        sync: false
      - key: BACK_SECRET_JWT
        sync: false
      - key: EMAIL_ADMIN
        sync: false
      - key: PASSWORD_ADMIN
        sync: false
      - key: PORT
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: api-news-interact
    env: docker
    plan: free
    dockerfilePath: ./api-news-interact/Dockerfile.prod
    dockerContext: ./api-news-interact
    autoDeploy: true
    envVars:
      - key: INTERACT_MONGODB_URI
        sync: false
      - key: INTERACT_SECRET_JWT
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: thenews
    env: docker
    plan: free
    dockerfilePath: ./nginx/Dockerfile.prod
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: VITE_API_BACK_URL
        sync: false
      - key: VITE_API_INTERACT_URL
        sync: false