FROM node:20-alpine AS build

ARG VITE_API_BACK_URL
ARG VITE_API_INTERACT_URL

ENV VITE_API_BACK_URL=$VITE_API_BACK_URL
ENV VITE_API_INTERACT_URL=$VITE_API_INTERACT_URL

WORKDIR /app
COPY ./api-news-front/package*.json ./
RUN npm install
COPY ./api-news-front . 
RUN npm run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /var/www/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]