# Etapa de build do front
FROM node:20-alpine AS build
WORKDIR /app
COPY ./api-news-front/package*.json ./
RUN npm install
COPY ./api-news-front . 
RUN npm run build


FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /var/www/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]